server:
  port: 8081
  servlet:
    context-path: /

# Spring配置
spring:
  application:
    name: decentralized-gaming-platform


  # 数据源配置 (使用MySQL数据库game)
  datasource:
    url: jdbc:mysql://localhost:3306/game?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # 禁用SQL初始化以避免Bean定义问题
  sql:
    init:
      mode: never

  # Redis配置（暂时禁用）
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  #     database: 0
  #     password: 
  #     timeout: 10000ms
  #     lettuce:
  #       pool:
  #         max-active: 100
  #         max-idle: 10
  #         min-idle: 0
  #         max-wait: -1ms

  # Thymeleaf配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    favicon:
      enabled: false

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*.xml

# 日志配置
logging:
  level:
    com.decentralized.gaming.platform: DEBUG
    org.springframework.web: INFO
    com.baomidou.mybatisplus.core: DEBUG
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
  # 禁用文件日志输出，只输出到控制台
  # file:
  #   name: logs/gaming-platform.log

# 应用配置
app:
  # 区块链配置
  blockchain:
    enabled: true  # 是否启用区块链功能 (临时禁用以便应用启动)
    networkUrl: http://localhost:8545
    chainId: 31337
    gasLimit: 300000
    gasPrice: 20000000000
    # 合约地址配置
    contracts:
      platformToken: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      gameNft: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
      agentNft: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
      marketplace: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
      rewards: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
    # 重试配置
    retry:
      max-attempts: 3
      delay-ms: 1000
      backoff-multiplier: 2
    # 缓存配置
    cache:
      balance-ttl: 300      # 余额缓存5分钟
      gas-price-ttl: 60     # Gas价格缓存1分钟
      block-number-ttl: 10  # 区块号缓存10秒

    # 合约信息配置
    contract-info:
      platform-token:
        name: "Platform Token"
        symbol: "PLT"
        decimals: 18
        type: "ERC20"
        total-supply: "1000000000000000000000000000"  # 1 billion tokens
        base-uri: "https://api.gaming-platform.com/metadata/token/"
      game-nft:
        name: "Game NFT"
        symbol: "GAME"
        type: "ERC721"
        base-uri: "https://api.gaming-platform.com/metadata/game/"
      agent-nft:
        name: "Agent NFT"
        symbol: "AGENT"
        type: "ERC721"
        base-uri: "https://api.gaming-platform.com/metadata/agent/"
      marketplace:
        name: "Marketplace"
        type: "Marketplace"
        fee-rate: "250"  # 2.5% fee (250 basis points)
        fee-recipient: "0x0000000000000000000000000000000000000000"
      rewards:
        name: "Rewards"
        type: "Rewards"

  # IPFS配置
  ipfs:
    # 统一网关键名：用于拼接 https 网关访问（读取/下载）
    gateway: https://ipfs.io/ipfs/
    # 本地 Kubo(IPFS) API 配置
    kubo:
      api-url: http://127.0.0.1:5001/api/v0
      enabled: true
    # Pinata 配置（优先用于上传/固定 pin）
    pinata:
      enabled: true
      base-url: https://api.pinata.cloud
      gateway: https://orange-rational-squirrel-965.mypinata.cloud/ipfs/
      jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJjNjJmMTdiYS1mNzQ2LTRmY2ItOTViYS02YTM1N2U5MWYwNWUiLCJlbWFpbCI6IjIwMjEyOTk0NTBAcXEuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiRlJBMSJ9LHsiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiTllDMSJ9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6IjZkYTBmMWU5ODkwOWI5ZjAxNTdhIiwic2NvcGVkS2V5U2VjcmV0IjoiOWIwNDhlZWZkZWIwMzM4M2JhNzI1NmIwODAxMzhlZDY1YzIwNTk2NmIwNmRhMzFkNzFhZDljYzk4ZTkxMGY4ZiIsImV4cCI6MTc5MTUzMDUzOH0.5sS7b6LVKElAxSY3RgwGGFA2EYsefPxv83gH8N1JsvQ
      api-key: 6da0f1e98909b9f0157a
      api-secret: 9b048eefdeb03383ba7256b080138ed65c205966b06da31d71ad9cc98e910f8f
  
  # AI配置
  ai:
    openai:
      api-key: YOUR_OPENAI_API_KEY
      model: gpt-4
      temperature: 0.7
  
  # 支付配置
  payment:
    stripe:
      public-key: pk_test_YOUR_STRIPE_PUBLIC_KEY
      secret-key: sk_test_YOUR_STRIPE_SECRET_KEY
  
  # 系统配置
  system:
    platform-token-symbol: PLT
    game-creation-cost: 100.0
    agent-upload-cost: 50.0
    marketplace-fee-rate: 0.025

  # JWT配置
  jwt:
    secret: decentralized-gaming-platform-secret-key-2024
    expiration: 86400000  # 86400000毫秒 = 24小时


# OpenAPI配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
